import { StyleSheet } from 'react-native';

import { palette } from '../../../shared/theme/palette';

export const progressScreenStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.background,
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    alignItems: 'center',
    padding: 20,
    gap: 18,
    paddingBottom: 28,
  },
  hero: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    gap: 8,
  },
  kicker: {
    color: palette.accentStrong,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  title: {
    color: palette.textPrimary,
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 36,
    textAlign: 'center',
    maxWidth: '100%',
  },
  subtitle: {
    color: palette.textSecondary,
    fontSize: 15,
    lineHeight: 23,
    textAlign: 'center',
    maxWidth: '100%',
  },
  summaryCard: {
    width: '100%',
    alignSelf: 'center',
    backgroundColor: palette.panelElevated,
    borderRadius: 28,
    padding: 20,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 16,
  },
  summaryTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  summaryLabel: {
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: '700',
  },
  summaryValue: {
    marginTop: 6,
    color: palette.textPrimary,
    fontSize: 38,
    fontWeight: '900',
  },
  summaryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: palette.overlayPill,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: palette.border,
  },
  summaryBadgeText: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  progressTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: palette.track,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: palette.accentStrong,
  },
  levelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  levelText: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  levelTrack: {
    height: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(130, 245, 208, 0.08)',
    overflow: 'hidden',
  },
  levelFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: 'rgba(130, 245, 208, 0.55)',
  },
  summaryMetaRow: {
    flexDirection: 'row',
    gap: 10,
  },
  miniMetric: {
    flex: 1,
    backgroundColor: palette.overlayPill,
    borderRadius: 18,
    paddingVertical: 13,
    paddingHorizontal: 10,
    gap: 5,
  },
  miniMetricHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  miniMetricValue: {
    color: palette.textPrimary,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  miniMetricLabel: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  grid: {
    width: '100%',
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  statCard: {
    flex: 1,
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 8,
  },
  statCardSuccess: {
    backgroundColor: palette.successPanel,
  },
  statCardWarning: {
    backgroundColor: palette.warningPanel,
  },
  statCardIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statValue: {
    color: palette.textPrimary,
    fontSize: 32,
    fontWeight: '900',
  },
  statLabel: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  panel: {
    width: '100%',
    alignSelf: 'center',
    backgroundColor: palette.panel,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 16,
  },
  panelTitle: {
    color: palette.textPrimary,
    fontSize: 20,
    fontWeight: '800',
  },
  panelBody: {
    color: palette.textSecondary,
    fontSize: 15,
    lineHeight: 23,
  },
  milestoneList: {
    gap: 10,
  },
  milestone: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 13,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.hairline,
    backgroundColor: 'rgba(7, 10, 14, 0.62)',
  },
  milestoneDone: {
    borderColor: 'rgba(130, 245, 208, 0.2)',
    backgroundColor: 'rgba(11, 29, 24, 0.72)',
  },
  milestoneIcon: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  milestoneCopy: {
    flex: 1,
    gap: 3,
  },
  milestoneTitle: {
    color: palette.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  milestoneBody: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  topicList: {
    gap: 12,
  },
  topicRow: {
    gap: 8,
  },
  topicRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  topicRowLabel: {
    color: palette.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  topicRowValue: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: '800',
  },
  topicRowTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: palette.track,
    overflow: 'hidden',
  },
  topicRowFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: palette.accentStrong,
  },
  topicRowMeta: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  progressPanelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  progressPanelLabel: {
    color: palette.textSecondary,
    fontSize: 14,
    fontWeight: '700',
  },
  progressPanelValue: {
    color: palette.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  breakdownRow: {
    gap: 8,
  },
  breakdownHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  breakdownLabel: {
    color: palette.textSecondary,
    fontSize: 14,
    fontWeight: '700',
  },
  breakdownValue: {
    color: palette.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  breakdownTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: palette.track,
    overflow: 'hidden',
  },
  breakdownFill: {
    height: '100%',
    borderRadius: 999,
  },
  tipCard: {
    backgroundColor: palette.overlayPill,
    borderRadius: 20,
    padding: 16,
    gap: 8,
  },
  tipLabel: {
    color: palette.accentStrong,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  tipText: {
    color: palette.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
  resetButton: {
    width: '100%',
    alignSelf: 'center',
    backgroundColor: palette.subtlePanel,
    borderRadius: 20,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: palette.border,
  },
  resetButtonText: {
    color: palette.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
});
