import { StyleSheet } from 'react-native';

import { palette } from '../../../shared/theme';

export const commandReferenceStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.background,
  },
  content: {
    alignSelf: 'center',
    gap: 18,
    paddingHorizontal: 0,
    paddingTop: 24,
  },
  hero: {
    gap: 10,
    paddingTop: 10,
  },
  hero__eyebrow: {
    color: palette.accentStrong,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 3.5,
    textTransform: 'uppercase',
  },
  hero__title: {
    color: palette.textPrimary,
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 38,
  },
  hero__body: {
    color: palette.textSecondary,
    fontSize: 16,
    lineHeight: 24,
  },
  summary: {
    flexDirection: 'row',
    gap: 10,
  },
  summaryPill: {
    flex: 1,
    gap: 5,
    padding: 16,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 22,
    backgroundColor: 'rgba(7, 10, 14, 0.78)',
  },
  summaryPill__value: {
    color: palette.textPrimary,
    fontSize: 24,
    fontWeight: '900',
  },
  summaryPill__label: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '800',
  },
  searchPanel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 24,
    backgroundColor: 'rgba(7, 10, 14, 0.88)',
  },
  searchPanel__icon: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: 'rgba(130, 245, 208, 0.08)',
  },
  searchPanel__input: {
    flex: 1,
    color: palette.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  filters: {
    gap: 10,
    paddingRight: 12,
  },
  sortRail: {
    flexDirection: 'row',
    gap: 10,
  },
  sortChip: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 999,
    backgroundColor: 'rgba(7, 10, 14, 0.74)',
  },
  sortChipActive: {
    borderColor: 'rgba(130, 245, 208, 0.32)',
    backgroundColor: 'rgba(130, 245, 208, 0.08)',
  },
  sortChip__text: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '900',
  },
  sortChip__textActive: {
    color: palette.accentStrong,
  },
  categoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 999,
    backgroundColor: palette.overlayPill,
  },
  categoryChipActive: {
    borderColor: 'rgba(130, 245, 208, 0.48)',
    backgroundColor: palette.accentStrong,
  },
  categoryChip__text: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: '800',
  },
  categoryChip__textActive: {
    color: palette.background,
  },
  resultHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  resultHeader__title: {
    color: palette.textPrimary,
    fontSize: 18,
    fontWeight: '900',
  },
  resultHeader__badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 999,
    backgroundColor: palette.overlayPill,
  },
  resultHeader__badgeText: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '800',
  },
  commandList: {
    gap: 14,
  },
  commandCard: {
    gap: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 26,
    backgroundColor: 'rgba(7, 10, 14, 0.86)',
  },
  commandCardPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.992 }],
  },
  commandCard__header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  commandCard__mark: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 42,
    height: 42,
    borderRadius: 16,
    backgroundColor: 'rgba(130, 245, 208, 0.08)',
  },
  commandCard__heading: {
    flex: 1,
    gap: 4,
  },
  commandCard__command: {
    color: palette.commandText,
    fontSize: 23,
    fontWeight: '900',
  },
  commandCard__meta: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '800',
  },
  commandCard__summary: {
    color: palette.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  commandCard__example: {
    gap: 8,
    padding: 14,
    borderRadius: 20,
    backgroundColor: palette.panelElevated,
  },
  commandCard__exampleLabel: {
    color: palette.accentStrong,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
  },
  commandCard__answer: {
    color: palette.textPrimary,
    fontSize: 16,
    fontWeight: '900',
  },
  commandCard__exampleBody: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  commandCard__footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  commandCard__chips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  commandCard__chip: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: palette.hairline,
    borderRadius: 999,
    backgroundColor: palette.overlayPill,
  },
  commandCard__chipText: {
    color: palette.textSecondary,
    fontSize: 11,
    fontWeight: '800',
  },
  commandCard__more: {
    color: palette.accentStrong,
    fontSize: 12,
    fontWeight: '900',
  },
  emptyState: {
    gap: 8,
    padding: 22,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 26,
    backgroundColor: 'rgba(7, 10, 14, 0.82)',
  },
  emptyState__title: {
    color: palette.textPrimary,
    fontSize: 20,
    fontWeight: '900',
  },
  emptyState__body: {
    color: palette.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  detailsScreen: {
    flex: 1,
    backgroundColor: palette.background,
  },
  detailsHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: palette.hairline,
    backgroundColor: 'rgba(1, 2, 3, 0.96)',
  },
  detailsHeader__copy: {
    flex: 1,
    gap: 4,
  },
  detailsHeader__eyebrow: {
    color: palette.accentStrong,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  detailsHeader__title: {
    color: palette.commandText,
    fontSize: 30,
    fontWeight: '900',
  },
  detailsHeader__closeButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: palette.hairline,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
  },
  detailsHeader__closeButtonText: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '800',
  },
  detailsContent: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 760,
    gap: 16,
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 42,
  },
  detailsHero: {
    gap: 14,
    padding: 20,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 28,
    backgroundColor: palette.panel,
  },
  detailsHero__meta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  detailsHero__metaText: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '800',
  },
  detailsHero__summary: {
    color: palette.textSecondary,
    fontSize: 15,
    lineHeight: 23,
  },
  detailsPanel: {
    gap: 12,
    padding: 18,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 26,
    backgroundColor: 'rgba(7, 10, 14, 0.86)',
  },
  detailsPanel__title: {
    color: palette.accentStrong,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.7,
    textTransform: 'uppercase',
  },
  answerRow: {
    padding: 14,
    borderRadius: 18,
    backgroundColor: palette.panelElevated,
  },
  answerRow__text: {
    color: palette.textPrimary,
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 21,
  },
  scenarioRow: {
    gap: 8,
    padding: 14,
    borderRadius: 20,
    backgroundColor: palette.panelElevated,
  },
  scenarioRow__header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  scenarioRow__category: {
    color: palette.accentStrong,
    fontSize: 11,
    fontWeight: '900',
  },
  scenarioRow__difficulty: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '800',
  },
  scenarioRow__question: {
    color: palette.textPrimary,
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 22,
  },
  scenarioRow__answer: {
    color: palette.commandText,
    fontSize: 14,
    fontWeight: '900',
    lineHeight: 20,
  },
  scenarioRow__body: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
});
