import { StyleSheet } from 'react-native';

import { palette } from '../../../shared/theme/palette';

export const learningCardStyles = StyleSheet.create({
  cardStage: {
    alignSelf: 'stretch',
    flex: 1,
    minHeight: 0,
    paddingBottom: 2,
    overflow: 'visible',
    position: 'relative',
    zIndex: 20,
    elevation: 20,
  },
  cardStage__queueCard: {
    position: 'absolute',
    left: 28,
    right: 28,
    top: 12,
    bottom: 22,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(92, 117, 159, 0.14)',
    backgroundColor: 'rgba(18, 29, 49, 0.34)',
    padding: 24,
  },
  cardStage__queueGlow: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 22,
    height: 92,
    borderRadius: 24,
    backgroundColor: 'rgba(130, 245, 208, 0.06)',
  },
  cardStage__queueEyebrow: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  cardStage__queueQuestion: {
    marginTop: 12,
    color: palette.textSecondary,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    maxWidth: '84%',
  },
  swipeCoach: {
    position: 'absolute',
    left: 22,
    right: 22,
    zIndex: 38,
    elevation: 38,
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(130, 245, 208, 0.2)',
    backgroundColor: 'rgba(7, 16, 26, 0.76)',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  swipeCoachUp: {
    top: 66,
  },
  swipeCoachDown: {
    bottom: 62,
    borderColor: 'rgba(244, 162, 97, 0.2)',
    backgroundColor: 'rgba(28, 18, 12, 0.72)',
  },
  swipeCoach__eyebrow: {
    color: palette.accentStrong,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  swipeCoach__label: {
    marginTop: 2,
    color: palette.textPrimary,
    fontSize: 13,
    fontWeight: '800',
  },
  card: {
    flex: 1,
    position: 'relative',
    borderRadius: 34,
    borderWidth: 1,
    borderColor: 'rgba(92, 117, 159, 0.18)',
    backgroundColor: palette.panelElevated,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.2,
    shadowRadius: 30,
    elevation: 24,
    zIndex: 24,
  },
  card__glowSuccess: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 34,
    borderWidth: 1.5,
    borderColor: palette.accentStrong,
    backgroundColor: 'rgba(130, 245, 208, 0.06)',
  },
  card__glowWarning: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 34,
    borderWidth: 1.5,
    borderColor: '#f4a261',
    backgroundColor: 'rgba(170, 98, 41, 0.08)',
  },
  card__swipeAuraTop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: '24%',
    backgroundColor: 'rgba(49, 141, 109, 0.24)',
  },
  card__swipeAuraBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '24%',
    backgroundColor: 'rgba(144, 85, 42, 0.24)',
  },
  cardFace: {
    ...StyleSheet.absoluteFillObject,
    padding: 21,
    backfaceVisibility: 'hidden',
  },
  cardFaceBack: {
    backgroundColor: palette.panelElevated,
  },
  cardFace__pressable: {
    flex: 1,
  },
  cardFace__metaRail: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 9,
  },
  cardFace__questionBlock: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: 10,
    paddingBottom: 16,
    gap: 12,
  },
  cardFace__questionBlockCompact: {
    paddingTop: 6,
    paddingBottom: 12,
    gap: 8,
  },
  cardFace__eyebrow: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.3,
    textTransform: 'uppercase',
  },
  cardFace__eyebrowCompact: {
    fontSize: 11,
  },
  cardFace__question: {
    maxWidth: '100%',
    color: palette.textPrimary,
    fontWeight: '900',
    flexShrink: 1,
  },
  cardFace__questionCompact: {
    maxWidth: '100%',
  },
  cardFace__footer: {
    gap: 8,
    paddingTop: 14,
  },
  cardFace__footerCompact: {
    gap: 8,
    paddingTop: 10,
  },
  cardFace__footerHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  cardFace__footerTitle: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: '800',
  },
  cardFace__footerTitleCompact: {
    fontSize: 12,
  },
  cardFace__manualButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(130, 245, 208, 0.2)',
    backgroundColor: 'rgba(130, 245, 208, 0.06)',
  },
  cardFace__manualButtonPressed: {
    opacity: 0.86,
  },
  cardFace__manualButtonText: {
    color: palette.textPrimary,
    fontSize: 11,
    fontWeight: '900',
  },
  cardFace__footerTrack: {
    height: 7,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: 'rgba(10, 20, 37, 0.44)',
  },
  cardFace__footerFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: 'rgba(130, 245, 208, 0.28)',
  },
  cardFaceBack__detailsWrap: {
    marginTop: 'auto',
    gap: 12,
    paddingTop: 12,
  },
  cardFaceBack__detailsHint: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(93, 118, 160, 0.18)',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
  },
  cardFaceBack__detailsHintText: {
    flex: 1,
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  cardFaceBack__actions: {
    flexDirection: 'row',
    gap: 10,
  },
  cardFaceBack__ghostButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.overlayPill,
  },
  cardFaceBack__ghostButtonText: {
    color: palette.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  cardFaceBack__primaryButton: {
    flex: 1.15,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: palette.accentStrong,
  },
  cardFaceBack__primaryButtonText: {
    color: palette.background,
    fontSize: 15,
    fontWeight: '900',
  },
  metaPill: {
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(158, 184, 214, 0.1)',
    backgroundColor: 'rgba(7, 10, 14, 0.62)',
  },
  metaPillCategory: {
    flex: 1.35,
  },
  metaPillIndex: {
    flex: 0.8,
  },
  metaPillDifficulty: {
    flex: 1,
  },
  metaPillCompact: {
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  metaPill__text: {
    color: palette.textSecondary,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  metaPill__textCompact: {
    fontSize: 10,
  },
  surface: {
    marginTop: 10,
    borderRadius: 20,
    padding: 13,
    gap: 7,
    borderWidth: 1,
    borderColor: 'rgba(96, 128, 168, 0.14)',
    backgroundColor: palette.footerPanel,
  },
  surfaceAccent: {
    marginTop: 15,
    backgroundColor: palette.answerPanel,
  },
  surfaceSubtle: {
    backgroundColor: palette.subtlePanel,
  },
  surface__head: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  surface__label: {
    color: palette.textMuted,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  surface__answer: {
    color: palette.textPrimary,
    fontSize: 19,
    fontWeight: '900',
    lineHeight: 25,
  },
  surface__body: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
});
